apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: mysql:8.0
            command:
            - /bin/sh
            - -c
            - |
              set -e
              DATE=`date +%Y%m%d%H%M%S`
              FILENAME=backup-$${DATE}.sql.gz
              mysqldump -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE | gzip > /backups/$${FILENAME}
              # Here you would typically upload to a cloud storage service
              # e.g., aws s3 cp /backups/$${FILENAME} s3://your-backup-bucket/
            env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: messaging-app-config
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: messaging-app-secrets
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: messaging-app-config
                  key: DB_NAME
            volumeMounts:
            - name: backup-volume
              mountPath: /backups
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
