apiVersion: v1
kind: ServiceAccount
metadata:
  name: messaging-app-sa
  namespace: messaging-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: messaging-app-role
  namespace: messaging-app
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: messaging-app-role-binding
  namespace: messaging-app
subjects:
- kind: ServiceAccount
  name: messaging-app-sa
  namespace: messaging-app
roleRef:
  kind: Role
  name: messaging-app-role
  apiGroup: rbac.authorization.k8s.io
