apiVersion: v1
kind: ResourceQuota
metadata:
  name: messaging-app-quota
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
    configmaps: "20"
    secrets: "20"
    services.loadbalancers: "2"
    services.nodeports: "2"
