apiVersion: v1
kind: Secret
metadata:
  name: messaging-app-secrets
type: Opaque
data:
  # Generate with: echo -n 'your-secret-key' | base64
  SECRET_KEY: "your-base64-encoded-secret-key"
  # Generate with: echo -n 'your-db-password' | base64
  DB_PASSWORD: "your-base64-encoded-db-password"
  # Add other sensitive data here
